// GATE 0 — byte-fidelity round-trip.
//
// pbi-cli writes PBIR JSON via Python's `json.dumps(data, indent=2,
// ensure_ascii=False) + "\n"` (UTF-8, no BOM). Power BI Desktop is sensitive
// to file-level diffs (line endings, escaping, indent style, trailing
// newline). If our writeJson produces output that differs from Python's by
// even one byte, downstream features will produce files Desktop subtly
// mishandles.
//
// This test reads reference fixtures generated by Python (in fixtures/
// byte-fidelity/), parses them via our readJson, writes them via our
// writeJson, and asserts byte-for-byte equality with the originals.
//
// Reference fixtures were generated with the exact Python code pbi-cli uses
// — see fixtures/byte-fidelity/generate.py (or the Phase 1 commit message).

import { readFileSync, readdirSync } from 'node:fs';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { readJson, writeJson } from '../../src/index.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FIXTURES_DIR = path.resolve(__dirname, '../../../../fixtures/byte-fidelity');

let tmp: string;

beforeAll(() => {
  tmp = mkdtempSync(path.join(tmpdir(), 'pbi-byte-'));
});

afterAll(() => {
  rmSync(tmp, { recursive: true, force: true });
});

describe('GATE 0: byte-fidelity vs Python json.dumps', () => {
  // Discover every .json file in fixtures/byte-fidelity/ at test time.
  const files = readdirSync(FIXTURES_DIR).filter((f) => f.endsWith('.json'));

  it('the fixture directory is not empty', () => {
    expect(files.length).toBeGreaterThanOrEqual(5);
  });

  it.each(files)('%s round-trips byte-identically', (filename) => {
    const refPath = path.join(FIXTURES_DIR, filename);
    const refBytes = readFileSync(refPath);

    // Parse + re-emit through our io.
    const data = readJson(refPath);
    const outPath = path.join(tmp, filename);
    writeJson(outPath, data);
    const outBytes = readFileSync(outPath);

    expect(outBytes.equals(refBytes)).toBe(true);
  });

  it('non-ASCII characters survive the round-trip without Unicode escaping', () => {
    const raw = readFileSync(path.join(FIXTURES_DIR, 'unicode.json'), 'utf-8');
    expect(raw).toContain('Café — Résumé');
    expect(raw).toContain('→');
    // The fixture should not contain \u escapes
    expect(raw).not.toMatch(/\\u/);
  });
});
