table Sales
	lineageTag: 11111111-1111-1111-1111-111111111111

	measure 'Total Amount' = SUM(Sales[Amount])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 22222222-2222-2222-2222-222222222222

	measure 'Total Orders' = DISTINCTCOUNT(Sales[OrderId])
		formatString: #,0
		lineageTag: 33333333-3333-3333-3333-333333333333

	measure AOV = DIVIDE([Total Amount], [Total Orders])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 44444444-4444-4444-4444-444444444444

	column OrderId
		dataType: int64
		summarizeBy: none
		sourceColumn: OrderId
		isHidden: true
		isKey: true

	column Amount
		dataType: decimal
		summarizeBy: sum
		sourceColumn: Amount

	column ProductKey
		dataType: int64
		summarizeBy: none
		sourceColumn: ProductKey
		isHidden: true

	column DateKey
		dataType: dateTime
		summarizeBy: none
		sourceColumn: DateKey
